# Generated by Django 5.2.4 on 2025-10-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
