# Generated by Django 5.2.4 on 2025-08-04 00:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("followers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Followe",
            new_name="Follow",
        ),
    ]
